"""
Enhanced Collaborative Orchestrator
Manages multi-agent workflows with intelligent collaboration and shared context
"""

from typing import Dict, Any, List, Optional
from agents.base_agent import SharedContext
from agents.collaborative_subject_expert import CollaborativeSubjectExpert
from agents.collaborative_assessment_agent import CollaborativeAssessmentAgent
from agents.collaborative_curriculum_planner import CollaborativeCurriculumPlanner
from agents.collaborative_feedback_agent import CollaborativeFeedbackAgent


class CollaborativeOrchestrator:
    """Advanced orchestrator that enables true multi-agent collaboration"""
    
    def __init__(self):
        self.shared_context = SharedContext()
        self.agents = self._initialize_agents()
        self.workflow_results = {}
    
    def _initialize_agents(self) -> Dict[str, Any]:
        """Initialize all collaborative agents with shared context"""
        agents = {
            "subject_expert": CollaborativeSubjectExpert(),
            "assessment_agent": CollaborativeAssessmentAgent(), 
            "curriculum_planner": CollaborativeCurriculumPlanner(),
            "feedback_agent": CollaborativeFeedbackAgent()
        }
        
        # Set shared context for all agents
        for agent in agents.values():
            agent.set_shared_context(self.shared_context)
        
        return agents
    
    def run_comprehensive_workflow(self, student_answer: str, sample_answer: str, 
                                 concept: str, **kwargs) -> Dict[str, Any]:
        """
        Run a comprehensive educational workflow with full agent collaboration
        
        Workflow Steps:
        1. Subject Expert explains the concept
        2. Assessment Agent evaluates student answer
        3. Feedback Agent provides detailed feedback using all context
        4. Curriculum Planner creates/adjusts study plan based on assessment
        5. Agents collaborate to refine outputs
        """
        
        print("🚀 Starting Collaborative Multi-Agent Workflow...")
        
        # Step 1: Subject Expert provides concept explanation
        print("📚 Step 1: Subject Expert analyzing concept...")
        explanation_result = self.agents["subject_expert"].process({
            "concept": concept,
            "student_level": kwargs.get("student_level", "high school")
        })
        
        self.workflow_results["explanation"] = explanation_result["explanation"]
        print(f"✅ Concept explanation generated by {explanation_result.get('collaboration_context', {}).get('agent_id', 'subject_expert')}")
        
        # Step 2: Assessment Agent evaluates student answer
        print("🔍 Step 2: Assessment Agent evaluating answer...")
        assessment_result = self.agents["assessment_agent"].process({
            "task_type": "assess_answer",
            "student_answer": student_answer,
            "sample_answer": sample_answer,
            "concept": concept
        })
        
        self.workflow_results["assessment"] = assessment_result["assessment"]
        print(f"✅ Assessment completed by {assessment_result.get('collaboration_context', {}).get('agent_id', 'assessment_agent')}")
        
        # Step 3: Feedback Agent provides comprehensive feedback
        print("💬 Step 3: Feedback Agent generating comprehensive feedback...")
        feedback_result = self.agents["feedback_agent"].process({
            "student_answer": student_answer,
            "expected_answer": sample_answer
        })
        
        self.workflow_results["feedback"] = feedback_result["feedback"]
        print(f"✅ Feedback generated by {feedback_result.get('collaboration_context', {}).get('agent_id', 'feedback_agent')}")
        
        # Step 4: Curriculum Planner creates adaptive study plan
        if kwargs.get("create_curriculum"):
            print("📅 Step 4: Curriculum Planner creating adaptive study plan...")
            curriculum_result = self.agents["curriculum_planner"].process({
                "subject": kwargs.get("subject", concept),
                "hours_per_day": kwargs.get("hours_per_day", 2),
                "exam_date": kwargs.get("exam_date", "2025-12-15")
            })
            
            self.workflow_results["curriculum_plan"] = curriculum_result["curriculum_plan"]
            print(f"✅ Curriculum plan created by {curriculum_result.get('collaboration_context', {}).get('agent_id', 'curriculum_planner')}")
        
        # Step 5: Request targeted questions if assessment shows weaknesses
        if "needs improvement" in assessment_result["assessment"].lower():
            print("🎯 Step 5: Generating targeted practice questions...")
            targeted_questions = self._generate_targeted_questions(concept, assessment_result["assessment"])
            self.workflow_results["targeted_questions"] = targeted_questions
            print("✅ Targeted questions generated for improvement areas")
        
        # Step 6: Generate collaboration summary
        collaboration_summary = self._generate_collaboration_summary()
        
        print("🎉 Multi-Agent Collaboration Complete!")
        
        return {
            **self.workflow_results,
            "collaboration_summary": collaboration_summary,
            "agent_interactions": self._get_agent_interaction_summary(),
            "shared_context_data": self._get_context_summary()
        }
    
    def run_curriculum_planning_workflow(self, subject: str, hours_per_day: float, 
                                       exam_date: str, assessment_data: Optional[Dict] = None) -> Dict[str, Any]:
        """Run curriculum planning workflow with assessment integration"""
        
        print("📚 Starting Curriculum Planning Workflow...")
        
        # If assessment data provided, store in context
        if assessment_data:
            self.shared_context.set("assessment_results", assessment_data, "external")
        
        # Generate curriculum plan
        curriculum_result = self.agents["curriculum_planner"].process({
            "subject": subject,
            "hours_per_day": hours_per_day,
            "exam_date": exam_date
        })
        
        # Request subject expert to provide learning objectives
        subject_objectives = self.agents["subject_expert"].process({
            "concept": subject,
            "task": "learning_objectives"
        })
        
        return {
            "curriculum_plan": curriculum_result["curriculum_plan"],
            "learning_objectives": subject_objectives["explanation"],
            "collaboration_summary": self._generate_collaboration_summary()
        }
    
    def run_assessment_workflow(self, topic: str, question_type: str = "mixed", 
                               num_questions: int = 5) -> Dict[str, Any]:
        """Run assessment generation workflow"""
        
        print("📝 Starting Assessment Generation Workflow...")
        
        # Generate concept explanation first
        explanation_result = self.agents["subject_expert"].process({
            "concept": topic
        })
        
        # Generate questions with context
        questions_result = self.agents["assessment_agent"].process({
            "task_type": "generate_questions",
            "topic": topic,
            "question_type": question_type,
            "num_questions": num_questions
        })
        
        return {
            "concept_explanation": explanation_result["explanation"],
            "exam_questions": questions_result["questions"],
            "collaboration_summary": self._generate_collaboration_summary()
        }
    
    def _generate_targeted_questions(self, concept: str, assessment_result: str) -> str:
        """Generate targeted questions for weak areas"""
        weak_areas = self._extract_weak_areas(assessment_result)
        
        targeted_questions_result = self.agents["assessment_agent"].collaborate_with(
            "curriculum_planner",
            "create_targeted_questions",
            {
                "topic": concept,
                "weak_areas": weak_areas,
                "assessment_context": assessment_result
            }
        )
        
        return targeted_questions_result
    
    def _extract_weak_areas(self, assessment_result: str) -> List[str]:
        """Extract weak areas from assessment result"""
        weak_indicators = ["missing", "incorrect", "needs improvement", "unclear", "confusion"]
        weak_areas = []
        
        lines = assessment_result.split('\n')
        for line in lines:
            for indicator in weak_indicators:
                if indicator in line.lower():
                    weak_areas.append(line.strip())
                    break
        
        return weak_areas[:3]  # Return top 3 weak areas
    
    def _generate_collaboration_summary(self) -> Dict[str, Any]:
        """Generate summary of agent collaborations"""
        total_messages = len(self.shared_context.messages)
        agents_involved = list(self.shared_context.agent_registry.keys())
        workflow_steps = len(self.shared_context.workflow_history)
        
        return {
            "total_agent_messages": total_messages,
            "agents_participated": agents_involved,
            "workflow_steps_completed": workflow_steps,
            "collaboration_success": True,
            "context_data_shared": len(self.shared_context.data)
        }
    
    def _get_agent_interaction_summary(self) -> List[Dict[str, Any]]:
        """Get summary of agent interactions"""
        interactions = []
        
        for message in self.shared_context.messages:
            interactions.append({
                "from": message.sender,
                "to": message.receiver,
                "type": message.message_type,
                "timestamp": message.timestamp.isoformat(),
                "content_preview": str(message.content)[:100] + "..." if len(str(message.content)) > 100 else str(message.content)
            })
        
        return interactions
    
    def _get_context_summary(self) -> Dict[str, Any]:
        """Get summary of shared context data"""
        context_summary = {}
        
        for key, data in self.shared_context.data.items():
            context_summary[key] = {
                "set_by": data["set_by"],
                "timestamp": data["timestamp"].isoformat(),
                "data_type": type(data["value"]).__name__,
                "content_length": len(str(data["value"]))
            }
        
        return context_summary
    
    def get_agent_status(self) -> Dict[str, Any]:
        """Get status of all agents"""
        status = {}
        
        for agent_id, agent in self.agents.items():
            status[agent_id] = {
                "specialization": agent.specialization,
                "messages_received": len(agent.inbox),
                "collaborations_initiated": len(agent.collaboration_history),
                "active": True
            }
        
        return status


# Backward compatibility function
def run_workflow(student_answer: str, sample_answer: str, concept: str) -> Dict[str, Any]:
    """Backward compatibility wrapper"""
    orchestrator = CollaborativeOrchestrator()
    result = orchestrator.run_comprehensive_workflow(student_answer, sample_answer, concept)
    
    # Return in original format for compatibility
    return {
        "explanation": result.get("explanation"),
        "assessment": result.get("assessment"),
        "feedback": result.get("feedback"),
        "collaboration_info": result.get("collaboration_summary")
    }